PrintDebugMsg         n

ServerSoftware        server-http2
ServerAddr            0.0.0.0
ServerPort            8443

DocumentRoot          ../../www/html
ScriptPath            ../../www/cgi
LogPath               logs
PidFilePath           pid

MaxConcurrentStreams  128

ListenBacklog         4096
TcpNoDelay            y

MaxAcceptConnections  5005

DataBufSize           16000   # 8192 16375
                              # OpenBSD: DataBufSize 2039

MaxCgiProc            15

Timeout               35       # seconds
TimeoutKeepAlive      200      # seconds
TimeoutCGI            5        # seconds
TimeoutPoll           10       # milliseconds

ClientMaxBodySize     1000000000

####### UsePHP: n, php-fpm, php-cgi #######
#UsePHP                php-cgi
#PathPHP               /usr/bin/php-cgi

UsePHP                php-fpm
PathPHP               127.0.0.1:9000  # [php-fpm: 127.0.0.1:9000 (/var/run/php-fpm.sock)]


fastcgi {
        ~/env  127.0.0.1:9002
}

scgi {
	~/scgi_test 127.0.0.1:9009
}

ShowMediaFiles       y   #  y/n

User                 root
Group                www-data
